modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="just_ctgui"
version="0.0.55"
displayName="Just CTGUI"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="300f20t, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.just_ctgui]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



