modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"

[[mods]]
modId="just_ctgui"
version="0.1.4"
displayName="Just CTGUI"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="300f20t, MCreator"
description="The Just Craft Tweaker GUI mod provides a visual recipe editor in minecraft using Craft Tweaker and a simple Zen Script programming language."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.just_ctgui]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"



